//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package WpfApplication2.Properties;

// ********* THIS FILE IS AUTO PORTED FROM C# USING CODEPORTING.COM *********




/**
     * <p>
     *   A strongly-typed resource class, for looking up localized strings, etc.
     * </p>
     */
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
@GeneratedCodeAttribute ("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")
@DebuggerNonUserCodeAttribute ()
@CompilerGeneratedAttribute ()
class Resources
{

    private static ResourceManager resourceMan;

    private static CultureInfo resourceCulture;

    @SuppressMessageAttribute ("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")
    Resources()
    {
    }

    /**
     * <p>
     *   Returns the cached ResourceManager instance used by this class.
     * </p>
     */
    @EditorBrowsableAttribute ()
    static ResourceManager getResourceManager()
    {
        if ((resourceMan == null))
        {
            ResourceManager temp = new ResourceManager("WpfApplication2.Properties.Resources", ms.typeOf(Resources.class).getAssembly());
            resourceMan = temp;
        }
        return resourceMan;
    }

    /**
     * <p>
     *   Overrides the current thread's CurrentUICulture property for all
     *   resource lookups using this strongly typed resource class.
     * </p>
     */
    @EditorBrowsableAttribute ()
    static CultureInfo getCulture()
    {
        return resourceCulture;
    }
    @EditorBrowsableAttribute ()
    static void setCulture(CultureInfo value)
    {
        resourceCulture = value;
    }
}

