//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package WpfApplication2.Properties;

// ********* THIS FILE IS AUTO PORTED FROM C# USING CODEPORTING.COM *********




@CompilerGeneratedAttribute ()
@GeneratedCodeAttribute ("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")
final partial class Settings extends ApplicationSettingsBase
{

    private static Settings defaultInstance = ((Settings)(ApplicationSettingsBase.Synchronized(new Settings())));

    public static Settings getDefault()
    {
        return defaultInstance;
    }
}

